### ISSUE TITLE
Multiple Definition of rpl-mrhof error

### ISSUE THREAD

**Issue by alifa2try** [SWNRG/contiki-malicious#1]
![image](https://user-images.githubusercontent.com/19759609/182192568-091fe7c3-adb3-4f98-8683-924b328628e6.png)

I ran into this error while compiling the 'rpl-udp-controller-data.c' file, while trying to simulate Selective Forwarding Attack. Please help me to resolve this issue.

**Comment by georgevio** [comment]
I just checked, it compiles ok, both with Z1 & sky mote (look the attachments)
Please, do the following:
1. run cooja from this https://github.com/SWNRG/contiki-standard-extra-functions
2. From inside the running cooja, look for the "udp-malicious-client.c" from the OTHER contiki folder (contiki-malicious).

![udp-malicious-client-SKY-MOTE](https://user-images.githubusercontent.com/5894074/182442800-8bf58eeb-7e14-45db-b708-dafe99a54063.png)
![udp-malicious-client-Z1](https://user-images.githubusercontent.com/5894074/182442807-443139f5-8057-4f1d-afb4-d2bd400abebd.png)

**Comment by alifa2try** [comment]
I did as instructed but Cooja is not opening

![image](https://user-images.githubusercontent.com/19759609/182507321-f22ffcc7-1894-4eea-aad9-b1f12c999715.png)

**Comment by alifa2try** [comment]
This is the terminal output:

init:

compile:

copy configs:

jar_cooja:
      [jar] Building jar: /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/dist/cooja.jar

jar:

init:

compile:

jar:

init:

mspsim:

init:

compile:

jar:

coffee:

init:

compile:
    [javac] Compiling 8 source files to /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/coffee-manager/build

configs:

jar:
      [jar] Building jar: /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/coffee-manager/coffee.jar
     [copy] Copying 1 file to /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/mspsim/lib

compile:

copy:

jar:

init:

compile:

jar:

init:

clean:
   [delete] Deleting directory /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/serial_socket/build

compile:
    [mkdir] Created dir: /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/serial_socket/build
    [javac] Compiling 2 source files to /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/serial_socket/build

jar:
      [jar] Building jar: /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/serial_socket/lib/serial_socket.jar

init:

compile:

jar:

init:

compile:

jar:

init:

clean:
   [delete] Deleting directory /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/powertracker/build

compile:
    [mkdir] Created dir: /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/powertracker/build
    [javac] Compiling 1 source file to /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/powertracker/build

jar:
      [jar] Building jar: /home/user/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja/apps/powertracker/lib/powertracker.jar

run:
     [java]  WARN [main] (Cooja.java:3172) - JAVA_HOME environment variable not set, Cooja motes may not compile
     [java]  INFO [AWT-EventQueue-0] (Cooja.java:2856) - External tools default settings: /external_tools_linux.config
     [java]  INFO [AWT-EventQueue-0] (Cooja.java:2886) - External tools user settings: /root/.cooja.user.properties
     [java] Exception in thread "AWT-EventQueue-0" java.lang.VerifyError: Bad type on operand stack
     [java] Exception Details:
     [java]   Location:
     [java]     Mobility.<init>(Lorg/contikios/cooja/Simulation;Lorg/contikios/cooja/Cooja;)V @65: invokespecial
     [java]   Reason:
     [java]     Type 'org/contikios/cooja/dialogs/MessageList' (current frame, stack[3]) is not assignable to 'java/awt/Component'
     [java]   Current Frame:
     [java]     bci: @65
     [java]     flags: { }
     [java]     locals: { 'Mobility', 'org/contikios/cooja/Simulation', 'org/contikios/cooja/Cooja' }
     [java]     stack: { 'Mobility', uninitialized 57, uninitialized 57, 'org/contikios/cooja/dialogs/MessageList' }
     [java]   Bytecode:
     [java]     0x0000000: 2a12 072c 03b7 0008 2a04 b500 092a 01b5
     [java]     0x0000010: 000a 2abb 000b 59b7 000c b500 0d2a bb00
     [java]     0x0000020: 0e59 2a09 b700 0fb5 0003 2a2b b500 042a
     [java]     0x0000030: b400 0d01 04b6 0010 2abb 0011 592a b400
     [java]     0x0000040: 0db7 0012 b600 1357 2ab4 000d bb00 1459
     [java]     0x0000050: b700 1512 16b6 0017 2bb6 0018 b600 19b6
     [java]     0x0000060: 001a b600 1bb2 001c bb00 1459 b700 1512
     [java]     0x0000070: 16b6 0017 2bb6 0018 b600 19b6 001a b600
     [java]     0x0000080: 1d2a 1101 f411 00c8 b600 1eb1          
     [java] 
     [java] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
     [java] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
     [java] 	at java.lang.Class.getConstructor0(Class.java:3075)
     [java] 	at java.lang.Class.getConstructor(Class.java:1825)
     [java] 	at org.contikios.cooja.Cooja.registerPlugin(Cooja.java:1930)
     [java] 	at org.contikios.cooja.Cooja.reparseProjectConfig(Cooja.java:1576)
     [java] 	at org.contikios.cooja.Cooja.<init>(Cooja.java:434)
     [java] 	at org.contikios.cooja.Cooja$30.run(Cooja.java:3322)
     [java] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
     [java] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
     [java] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
     [java] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
     [java] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [java] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

BUILD SUCCESSFUL
Total time: 7 seconds
user@instant-contiki:~/RPL_Attacks/SFA-I/contiki-standard-extra-functions/tools/cooja$

**Comment by georgevio** [comment]
The last message "BUILD SUCCESSFUL" means that cooja is compiling ok. It should just pop up the GUI. Please, try an up-to-date contiki 3.0 version. Does it compile and run ok?

**Comment by alifa2try** [comment]
Yes, I am using Contiki 3.0, but somehow it doesn't pop the GUI.

**Comment by georgevio** [comment]
Strange! 
if it is a virtual machine, check that you have enough RAM. Check if the graphics driver is ok. Check if all prerequisites for contiki/cooja are met (read carefully the readme instructions). Make sure you compile contiki correctly.
Bottomline: It looks like a contiki/cooja problem in general, not this altered contiki version problem...
